# Generated by Django 4.2.7 on 2024-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml_app', '0004_cadastraldeviation_sub_division_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastraldeviation',
            name='ward2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
