# Generated by Django 4.2.7 on 2024-07-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml_app', '0005_cadastraldeviation_ward2'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrusionmaster',
            name='sub_division_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intrusionmaster',
            name='town_survey_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intrusionmaster',
            name='village_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intrusionmaster',
            name='ward2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intrusionmaster',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
