from django.contrib import admin
from . models import *

admin.site.register(WardRegion)
admin.site.register(TalukMaster)
admin.site.register(ListType)
admin.site.register(ListOFValues)
admin.site.register(TownMaster)
admin.site.register(StreetMaster)
admin.site.register(CadastralEntry)
admin.site.register(CadastralMaster)
admin.site.register(CadastralDeviation)
admin.site.register(DeviationValue)
admin.site.register(SubCadastralLine)
admin.site.register(BlockMaster)
admin.site.register(SurveyMaster)
admin.site.register(SubCadastralEntry)
admin.site.register(IntrusionMaster)
admin.site.register(IntrusionChild)
admin.site.register(ListofValuesExcelTable)
admin.site.register(StreetExcelTable)
admin.site.register(CadastralMasterExcelTable)
admin.site.register(CadastralEntryExcelTable)
admin.site.register(CadastralDeviationExcelTable)
admin.site.register(IntrusionMasterExcelTable)
admin.site.register(CadastralMasterKMLTable)
admin.site.register(EnchrochKMLTable)
admin.site.register(IntrusionKMLTable)
admin.site.register(BoundaryKMLTable)
# admin.site.register(SettingsModel)
